### ISSUE TITLE
[BUG] Crypto Link UPLINK 

### ISSUE THREAD

**Issue by AnimusXCASH** [Crypto-Link-Payments/crypto-link#87]
Some channels for CL feed can not get processed as it does not have access to them. Manage the NoneType error. 

 

> File "/root/crypto-link/cogs/utils/systemMessaages.py", line 470, in explorer_messages
>     await explorer_channel.send(message)
> AttributeError: 'NoneType' object has no attribute 'send'
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/root/crypto-link/CLENVNEW/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 939, in invoke
>     await ctx.command.invoke(ctx)
>   File "/root/crypto-link/CLENVNEW/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1342, in invoke
>     await injected(ctx.args, **ctx.kwargs)
>   File "/root/crypto-link/CLENVNEW/lib/python3.8/site-packages/discord/ext/commands/core.py", line 94, in wrapped
>     raise CommandInvokeError(exc) from exc
> discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'NoneType' object has no attribute 'send'

**Comment by AnimusXCASH** [comment]
fixed.
